### ISSUE TITLE
Collect SQL 2019 new Linux DMV's

### ISSUE THREAD

**Issue by jaynar-cts1** [microsoft/DiagManager#43] opened 2019-10-30 22:17 UTC
Collect SQL 2019 new Linux DMV's

sys.dm_pal_net_stats
sys.dm_pal_disk_stats
sys.dm_pal_vm_stats
sys.dm_pal_cpu_stats

**Comment by PiJoCoder** [comment] 2022-04-20 22:22
Duplicate of #113 . Closing this.

**Closed by PiJoCoder** 2022-04-20 22:22 UTC
Labels: enhancement, linux
